# Site settings
title: tldr{Code}
email: webmaster@tldrcode.com
description: >
  Don't waste time with syntax; unleash the code!
baseurl: ""
url: "http://tldrcode.com"
twitter_username: https://twitter.com/tldrcode
github_username:  https://github.com/tldrcode

# Build settings
markdown: kramdown

highlighter: pygments

collections:
  languages:
    output: true

exclude: ['README.md', 'Vagrantfile', 'CNAME', 'LICENSE']
