# Site settings
title: tldr{Code}
email: webmaster@tldrcode.com
description: > # this means to ignore newlines until "baseurl:"
  Don't waste time with syntax; unleash the code!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tldrcode.com" # the base hostname & protocol for your site
twitter_username: https://twitter.com/tldrcode
github_username:  https://github.com/tldrcode

# Build settings
markdown: kramdown

highlighter: pygments

collections:
  languages:
    output: true
